Upload Task4
TheRaymondPlex/Tasks pull request #3
Opened 2022-10-17 12:45 UTC by TheRaymondPlex

Uploading Task4 to master branch

2022-10-19 13:34 UTC, nashalda requested changes

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/controllers/UserController.php
> +        if ($gender != 'male' && $gender != 'female') {
Убрать хардкод - обсудили

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/controllers/UserController.php
> +            $result[] = 'Incorrect data in gender selector!';
Переименовтаь $result - обсудили

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/controllers/UserController.php
> +    public function dataModify($data): string
проверь везде

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/controllers/UserController.php
> +            $decoded = json_decode($result, true);
$decoded - плохое название переменной, даже учитывая, что она временная

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/core/View.php
> +    public static function showErrorPage($code) {
если пользователю вернётся код ошибки, но не 404, то он увидит.... ничего он не увидит.
Надо подумать над логикой работы метода и изменить её

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/core/View.php
> +        extract($vars);
extract - небезопасная функция для работы с пользовательскими данными. Без крайней необходимости пользоваться ею не стоит. Попробуй от неё избавиться

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/core/View.php
> +        $this->path = $route['controller'].'/'.$route['action'];
.'/'. - отбивки пробелами добавь

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/lib/Db.php
> +class Db
базу данных мы же не используем в этом задании. Удали всё, что с ней связано

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/views/user/create.php
> +            <label for="Select" class="form-label">Gender</label>
посмоти инфу про тег <label и внеси изменения в код

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/controllers/UserController.php
> +                foreach ($errors as $key => $error) {
это должен быть отдельный метод, который будет объединять ошибки - что-то вроде 
convertErrorsToList
combineErrors

почитай про принципы SOLID - будем о них беседовать

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/controllers/UserController.php
> +        } else $this->view->render('Создать пользователя');
лучше добавить { }  - об этом беседовали

2022-10-19 13:34 UTC, nashalda commented on task4.com/application/views/layouts/default.php
> +    <link rel="stylesheet" href="/../public/css/style.css">
/.. - так делать неправильно
почитай про абсолютные и относителбные пути и тег link

2022-10-26 06:49 UTC, nashalda requested changes

2022-10-26 06:49 UTC, nashalda commented on task4.com/application/views/user/edit.php
> +            <label for="InputName" class="form-label">Name</label>
ещё раз прочитай про <label>, его аттрибут for

2022-10-26 06:49 UTC, nashalda commented on task4.com/application/views/user/edit.php
> +                    echo ucfirst($gender) . '</option>';
https://w3codegenerator.com/article/how-to-display-select-option-of-select-tag-as-selected-using-foreach-method-in-php - используй способ №4 из статьи

2022-10-26 06:49 UTC, nashalda commented on task4.com/application/core/Controller.php
> +    protected const GENDERS = [
пока чуть неправильно работаешь с <select>

давай сделаем массив
protected const GENDERS = [
        'male' => 'Мужчина',
        'female' => 'Женщина'
    ];

и 

    protected const STATUSES = [
        'active' => 'Активный',
        'inactive' => 'Неактивный'
    ];

потом в шаблонах используй вот отсюда  метод №4 - https://w3codegenerator.com/article/how-to-display-select-option-of-select-tag-as-selected-using-foreach-method-in-php

2022-10-26 17:05 UTC, TheRaymondPlex commented on task4.com/application/views/user/edit.php
> +            <label for="InputName" class="form-label">Name</label>
Я забыл поменять это в edit.php ^_^, а то поменял только в create.php.
А вообще, да, я почитал: во-первых можно без for в принципе, если input находится прямо внутри label.
Во-вторых, если уж for есть, то там должно быть id того input, к которому этот label привязываем.

2022-10-28 05:53 UTC, nashalda requested changes

2022-10-28 05:53 UTC, nashalda commented on .gitignore
>  .idea
index.php
.htaccess
composer.json
README.md
лежат на одном уровне
то есть у тебя должна получиться примерно такая структура
![image](https://user-images.githubusercontent.com/15914080/198511504-f46302b9-d2c8-4878-866f-e1c068399f18.png)

2022-10-28 05:53 UTC, nashalda commented on .gitignore
>  # Env file
папка vendor в git не загружается никогда

2022-10-28 05:53 UTC, nashalda commented on README.md
> +# Tasks
README.md не к этому заданию

И в нём должна быть прописана последовательность команд, чтобы установить проект - Run the application или Installation (без разницы как назвать)

2022-10-28 05:53 UTC, nashalda commented on .gitignore
> -.env
training-mvc.com - тоже явно не отюда эта директория

2022-10-28 05:53 UTC, nashalda commented on .gitignore
> +.env
проект не запускается ((
![image](https://user-images.githubusercontent.com/15914080/198512911-daf2089f-45c8-40f2-a444-eb4d98ace9b4.png)

2022-10-28 05:53 UTC, nashalda commented on .gitignore
> +.env
почитай про .env и .env.example

2022-11-02 09:45 UTC, nashalda requested changes

2022-11-02 09:45 UTC, nashalda commented on task4.com/README.md
> +![Innowise Group Logo](public/inno-logo.png)
зедсь НЕ описываем как устанавливать веб-сервер, так как он у каждого свой. Здесь описываем установку проекта
Rename `.env.example` file to `.env`.
 Fill the required fields in `.env` file with correct data.
install composer dependencies - composer install

2022-11-02 09:45 UTC, nashalda commented on task4.com/README.md
> +![Innowise Group Logo](public/inno-logo.png)
графические файлы складываем в /assets/images/

2022-11-02 09:45 UTC, nashalda commented on task4.com/application/models/Main.php
> +        $curl = curl_init(getenv('API') . '?page=' . $page . '&access-token=' . getenv('ACCESS_TOKEN'));
при неправильных кредах пользователю не выводится никакого сообщения типа "не могу получить данные из API"

2022-11-02 09:45 UTC, nashalda commented on task4.com/application/views/main/index.php
> +        <a href="/<?= $data['page'] + 1 ?>" class="btn btn-dark" role="button" data-bs-toggle="button">Next</a>
кнопка всегда активна, так не должно быть

2022-11-02 09:45 UTC, nashalda commented on task4.com/application/views/user/edit.php
> +                    $selected = ($key == $data['user']['gender']) ? 'selected="selected"' : '';
сравнивай строго

2022-11-02 09:45 UTC, nashalda commented on task4.com/application/views/user/edit.php
> +    <form action="/user/update" method="post">
![image](https://user-images.githubusercontent.com/15914080/199455482-06cb9254-d0e3-40a9-8b39-536536e94931.png)
делай подбный же action "/user/update/ххх" , а hidden поле убери

2022-11-03 09:53 UTC, merged