Upload Task5
TheRaymondPlex/Tasks pull request #5
Opened 2022-10-26 16:59 UTC by TheRaymondPlex

2022-10-28 07:47 UTC, nashalda requested changes

2022-10-28 07:47 UTC, nashalda commented on task5.com/application/lib/FileChecker.php
> +                $metaAsString .= "<b>" . $upKey . "</b>: " . $meta . "\n";
надо сделать рекурсию

2022-10-28 07:47 UTC, nashalda commented on task5.com/application/lib/FileChecker.php
> +                $metaAsString .= "<b>" . $upKey . "</b>: " . $meta . "\n";
здесь особо нет необходимости использовать html теги. 
Когда тебе понадобится поменять внешний вид вывода мета данных о файле (например добавить почёркивание) последнее куда ты полезешь будет файл application/lib/FileChecker.php

2022-10-28 07:47 UTC, nashalda commented on task5.com/application/lib/FileChecker.php
> +    private static function composingImageMetaData(string $upload): string
соответственно метод должен возвращать массив

2022-10-28 07:47 UTC, nashalda commented on task5.com/application/views/files/index.twig
> +                    <th scope="col">Action</th>
У кнопок в этой колонке есть говорящие названия Download, Remove, поэтому по юзабилити особо нет смысла давать этой коолонке имя

2022-10-28 07:47 UTC, nashalda commented on task5.com/application/views/files/index.twig
> +            <h1 style="text-align: center">No files!</h1>
<  h1> может быть на странцие только один

2022-10-28 07:47 UTC, nashalda commented on task5.com/application/core/Controller.php
> +        $path = 'application\models\\' . ucfirst($modelName);
ath = 'application\models\\' .

здесь точно это нужно \\ ?

2022-10-28 07:47 UTC, nashalda commented on task5.com/public/js/FileValidation.js
> +            if (fsize >= 1000000) {
1000000 - я думаю ты знаешь, что надо делать ;)

2022-10-28 07:47 UTC, nashalda commented on task5.com/public/js/FileValidation.js
> +                fi.value = '';
fi.value - вообще непонятно что здесь содержится((

2022-10-28 07:47 UTC, nashalda commented on task5.com/public/js/FileValidation.js
> +    const allowedTexts = /(\.txt|\.doc|\.docx)$/i;
allowedTexts => allowedTextTypes

allowedImages аналогично

2022-11-01 12:47 UTC, TheRaymondPlex commented on task5.com/application/core/Controller.php
> +        $path = 'application\models\\' . ucfirst($modelName);
Точно нужно, так как здесь обратные слеши. Если убрать, то символ ' будет экранироваться. А так \\ экранируется один нужный бэкслеш.

2022-11-01 13:04 UTC, TheRaymondPlex commented on task5.com/public/js/FileValidation.js
> +    const allowedTexts = /(\.txt|\.doc|\.docx)$/i;
Не совсем понял тут..
Как ключ => значение надо?

2022-11-07 14:48 UTC, nashalda requested changes

2022-11-07 14:48 UTC, nashalda commented on task5.com/application/controllers/FilesController.php
> +                mkdir($uploadsDirPath, 0777, true);
тем не менее нужно обрабатывать ошибку, если невозможно создать директорию

2022-11-07 14:48 UTC, nashalda commented on task5.com/application/controllers/FilesController.php
> +                mkdir($uploadsDirPath, 0777, true);
смотри в сторону RuntimeException

2022-11-07 14:48 UTC, nashalda commented on task5.com/index.php
> +session_start();
это здесь нужно
session_start();
?

2022-11-07 14:48 UTC, nashalda commented on task5.com/application/controllers/FilesController.php
> +            return true;
после редиректа можем написать 
return 'В космос';

2022-11-07 14:48 UTC, nashalda commented on task5.com/application/controllers/FilesController.php
> +            return true;
он здесь точно нужен?

2022-11-07 15:07 UTC, TheRaymondPlex commented on task5.com/application/controllers/FilesController.php
> +                mkdir($uploadsDirPath, 0777, true);
Аа, блин, точно!)

2022-11-07 15:08 UTC, TheRaymondPlex commented on task5.com/application/controllers/FilesController.php
> +            return true;
Не нужен )

2022-11-09 09:51 UTC, merged